TEMPLATES = {
    "en": {
        "lang_confirm": "Sure Boss. I'll speak in English. How can I help you?",
        "open_site": "Opening {site} Boss.",
        "open_app": "Opening {app} Boss.",
        "close_success": "Closed {target} successfully.",
        "close_fail": "Could not close {target}.",
        "folder_created": "Folder {name} Created successfully.",
        "folder_create_fail": "Failed to create folder {name}.",
        "file_created": "File {name} Created successfully.",
        "file_create_fail": "Failed to create file {name}.",
        "rename_success": "Renamed {src} to {dest} successfully.",
        "rename_fail": "Failed to rename {src} to {dest}.",
        "delete_success": "Deleted {target} successfully.",
        "delete_fail": "Failed to delete {target}.",
        "website_created": "Boss, the website has been created successfully. The server is running. Browser opened.",
        "stop_reply": "Stopped, Boss.",
        "clarify_open": "Which application or website should I open?",
        "clarify_close": "Which application should I close?",
        "clarify_general": "I'm not sure I understood that. Could you please be more specific?",
        "risk_med": "Are you sure you want to perform this operation?",
        "risk_high": "Warning: This is a high-risk operation. Do you want to proceed?",
        "unknown_error": "Sorry, I encountered an internal error processing that."
    },
    "te": {
        "lang_confirm": "సరే బాస్. ఇక నుంచి తెలుగులో మాట్లాడతాను. మీకు ఏం సహాయం కావాలి?",
        "open_site": "{site} ఓపెన్ చేస్తున్నాను బాస్.",
        "open_app": "{app} ఓపెన్ చేస్తున్నాను బాస్.",
        "close_success": "{target} విజయవంతంగా మూసివేయబడింది.",
        "close_fail": "{target} మూసివేయడం సాధ్యం కాలేదు.",
        "folder_created": "ఫోల్డర్ {name} విజయవంతంగా సృష్టించబడింది.",
        "folder_create_fail": "ఫోల్డర్ {name} సృష్టించడం విఫలమైంది.",
        "file_created": "ఫైల్ {name} విజయవంతంగా సృష్టించబడింది.",
        "file_create_fail": "ఫైల్ {name} సృష్టించడం విఫలమైంది.",
        "rename_success": "{src} పేరు విజయవంతంగా {dest} గా మార్చబడింది.",
        "rename_fail": "{src} పేరు మార్చడం విఫలమైంది.",
        "delete_success": "{target} విజయవంతంగా తొలగించబడింది.",
        "delete_fail": "{target} తొలగించడం విఫలమైంది.",
        "website_created": "బాస్, వెబ్‌సైట్ విజయవంతంగా సృష్టించబడింది. సర్వర్ నడుస్తోంది. బ్రౌజర్ తెరవబడింది.",
        "stop_reply": "సరే బాస్, ఆపుతున్నాను.",
        "clarify_open": "నేను ఏ అప్లికేషన్ లేదా వెబ్‌సైట్ తెరవాలి?",
        "clarify_close": "నేను ఏ అప్లికేషన్ మూసివేయాలి?",
        "clarify_general": "క్షమించండి బాస్, ఆ ఆదేశాన్ని ఎలా అమలు చేయాలో నాకు తెలియదు. దయచేసి స్పష్టం చేయగలరా?",
        "risk_med": "మీరు ఖచ్చితంగా ఈ ఆపరేషన్ చేయాలనుకుంటున్నారా?",
        "risk_high": "హెచ్చరిక: ఇది అధిక ప్రమాదం ఉన్న ఆపరేషన్. మీరు కొనసాగించాలనుకుంటున్నారా?",
        "unknown_error": "క్షమించండి, దీనిని ప్రాసెస్ చేయడంలో అంతర్గత లోపం ఏర్పడింది."
    },
    "hi": {
        "lang_confirm": "ठीक है बॉस। अब से मैं हिंदी में बात करूंगा। मैं आपकी कैसे मदद कर सकता हूँ?",
        "open_site": "{site} खोल रहा हूँ बॉस।",
        "open_app": "{app} खोल रहा हूँ बॉस।",
        "close_success": "{target} सफलतापूर्वक बंद कर दिया गया है।",
        "close_fail": "{target} को बंद नहीं किया जा सका।",
        "folder_created": "फ़ोल्डर {name} सफलतापूर्वक बनाया गया।",
        "folder_create_fail": "फ़ोल्डर {name} बनाने में विफल।",
        "file_created": "फ़ाइल {name} सफलतापूर्वक बनाई गई।",
        "file_create_fail": "फ़ाइल {name} बनाने में विफल।",
        "rename_success": "{src} का नाम बदलकर सफलतापूर्वक {dest} कर दिया गया है।",
        "rename_fail": "{src} का नाम बदलने में विफल।",
        "delete_success": "{target} सफलतापूर्वक हटा दिया गया।",
        "delete_fail": "{target} को हटाने में विफल।",
        "website_created": "बॉस, वेबसाइट सफलतापूर्वक बन गई है। सर्वर चल रहा है। ब्राउज़र खुल गया है।",
        "stop_reply": "ठीक है बॉस, रोक रहा हूँ।",
        "clarify_open": "मुझे कौन सा एप्लिकेशन या वेबसाइट खोलनी चाहिए?",
        "clarify_close": "मुझे कौन सा एप्लिकेशन बंद करना चाहिए?",
        "clarify_general": "मुझे क्षमा करें बॉस, मुझे समझ नहीं आया। क्या आप कृपया स्पष्ट कर सकते हैं?",
        "risk_med": "क्या आप वाकई यह ऑपरेशन करना चाहते हैं?",
        "risk_high": "चेतावनी: यह एक उच्च जोखिम वाला ऑपरेशन है। क्या आप आगे बढ़ना चाहते हैं?",
        "unknown_error": "क्षमा करें, इसे संसाधित करने में एक आंतरिक त्रुटि हुई है।"
    },
    "ta": {
        "lang_confirm": "சரி பாஸ். இனிமேல் நான் தமிழில் பேசுவேன். நான் உங்களுக்கு எப்படி உதவலாம்?",
        "open_site": "{site}-ஐ திறக்கிறேன் பாஸ்.",
        "open_app": "{app}-ஐ திறக்கிறேன் பாஸ்.",
        "close_success": "{target} வெற்றிகரமாக மூடப்பட்டது.",
        "close_fail": "{target}-ஐ மூட முடியவில்லை.",
        "folder_created": "கோப்புறை {name} வெற்றிகரமாக உருவாக்கப்பட்டது.",
        "folder_create_fail": "கோப்புறை {name} உருவாக்கத் தவறியது.",
        "file_created": "கோப்பு {name} வெற்றிகரமாக உருவாக்கப்பட்டது.",
        "file_create_fail": "கோப்பு {name} உருவாக்கத் தவறியது.",
        "rename_success": "{src} வெற்றிகரமாக {dest} என பெயர் மாற்றப்பட்டது.",
        "rename_fail": "{src} பெயர் மாற்றத் தவறியது.",
        "delete_success": "{target} வெற்றிகரமாக நீக்கப்பட்டது.",
        "delete_fail": "{target} நீக்கத் தவறியது.",
        "website_created": "பாஸ், வலைத்தளம் வெற்றிகரமாக உருவாக்கப்பட்டது. சர்வர் இயங்குகிறது. உலாவி திறக்கப்பட்டது.",
        "stop_reply": "சரி பாஸ், நிறுத்துகிறேன்.",
        "clarify_open": "நான் எந்த பயன்பாடு அல்லது வலைத்தளத்தைத் திறக்க வேண்டும்?",
        "clarify_close": "நான் எந்த பயன்பாட்டை மூட வேண்டும்?",
        "clarify_general": "மன்னிக்கவும் பாஸ், அந்த கட்டளையை எவ்வாறு செயல்படுத்துவது என்று எனக்குத் தெரியவில்லை. தயவுசெய்து தெளிவுபடுத்த முடியுமா?",
        "risk_med": "இந்த செயல்பாட்டை நீங்கள் நிச்சயமாக செய்ய விரும்புகிறீர்களா?",
        "risk_high": "எச்சரிக்கை: இது அதிக ஆபத்துள்ள செயல்பாடு. நீங்கள் தொடர விரும்புகிறீர்களா?",
        "unknown_error": "மன்னிக்கவும், இதைச் செயலாக்குவதில் உள் பிழை ஏற்பட்டது."
    },
    "kn": {
        "lang_confirm": "ಸರಿ ಬಾಸ್. ಇನ್ನು ಮುಂದೆ ನಾನು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡುತ್ತೇನೆ. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
        "open_site": "{site} ತೆರೆಯುತ್ತಿದ್ದೇನೆ ಬಾಸ್.",
        "open_app": "{app} ತೆರೆಯುತ್ತಿದ್ದೇನೆ ಬಾಸ್.",
        "close_success": "{target} ಯಶಸ್ವಿಯಾಗಿ ಮುಚ್ಚಲಾಗಿದೆ.",
        "close_fail": "{target} ಮುಚ್ಚಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
        "folder_created": "ಫೋಲ್ಡರ್ {name} ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ.",
        "folder_create_fail": "ಫೋಲ್ಡರ್ {name} ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ.",
        "file_created": "ಫೈಲ್ {name} ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ.",
        "file_create_fail": "ಫೈಲ್ {name} ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ.",
        "rename_success": "{src} ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ {dest} ಗೆ ಮರುಹೆಸರಿಸಲಾಗಿದೆ.",
        "rename_fail": "{src} ಮರುಹೆಸರಿಸಲು ವಿಫಲವಾಗಿದೆ.",
        "delete_success": "{target} ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ.",
        "delete_fail": "{target} ಅಳಿಸಲು ವಿಫಲವಾಗಿದೆ.",
        "website_created": "ಬಾಸ್, ವೆಬ್‌ಸೈಟ್ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ. ಸರ್ವರ್ ಚಾಲನೆಯಲ್ಲಿದೆ. ಬ್ರೌಸರ್ ತೆರೆಯಲಾಗಿದೆ.",
        "stop_reply": "ಸರಿ ಬಾಸ್, ನಿಲ್ಲಿಸುತ್ತಿದ್ದೇನೆ.",
        "clarify_open": "ನಾನು ಯಾವ ಅಪ್ಲಿಕೇಶನ್ ಅಥವಾ ವೆಬ್‌ಸೈಟ್ ತೆರೆಯಬೇಕು?",
        "clarify_close": "ನಾನು ಯಾವ ಅಪ್ಲಿಕೇಶನ್ ಮುಚ್ಚಬೇಕು?",
        "clarify_general": "ಕ್ಷಮಿಸಿ ಬಾಸ್, ಆ ಆಜ್ಞೆಯನ್ನು ಹೇಗೆ ಕಾರ್ಯಗತಗೊಳಿಸಬೇಕೆಂದು ನನಗೆ ಖಚಿತವಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ಪಷ್ಟಪಡಿಸುವಿರಾ?",
        "risk_med": "ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಈ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಮಾಡಲು ಬಯಸುತ್ತೀರಾ?",
        "risk_high": "ಎಚ್ಚರಿಕೆ: ಇದು ಹೆಚ್ಚಿನ ಅಪಾಯದ ಕಾರ್ಯಾಚರಣೆಯಾಗಿದೆ. ನೀವು ಮುಂದುವರಿಯಲು ಬಯಸುವಿರಾ?",
        "unknown_error": "ಕ್ಷಮಿಸಿ, ಇದನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವಲ್ಲಿ ಆಂತರಿಕ ದೋಷ ಸಂಭವಿಸಿದೆ."
    }
}
