from enum import Enum

class IntentType(str, Enum):
    STOP = "STOP"
    LANGUAGE_SWITCH = "LANGUAGE_SWITCH"
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    CREATE = "CREATE"
    DELETE = "DELETE"
    MOVE = "MOVE"
    COPY = "COPY"
    RENAME = "RENAME"
    CREATE_PROJECT = "CREATE_PROJECT"
    APP_CONTROL = "APP_CONTROL"
    SEARCH = "SEARCH"
    KNOWLEDGE = "KNOWLEDGE"
    CONVERSATION = "CONVERSATION"
    UNKNOWN = "UNKNOWN"
    CLARIFICATION = "CLARIFICATION"
